apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: toharikrdemo 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: toharikrdemo 
    spec:
      containers:
        - name: toharikrdemo 
          image: devopsazure66containerregistry.azurecr.io/toharikrdemo
          ports:
          - containerPort: 80
